apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dojo-user-api
  annotations:
    run.googleapis.com/invoker-iam-disabled: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        run.googleapis.com/vpc-egress: "private-ranges-only"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - name: main-app
          image: MAIN_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: LOGGING_LEVEL
              valueFrom:
                secretKeyRef:
                  name: logging-level
                  key: latest
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: latest
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: latest
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: latest
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: latest
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-host
                  key: latest
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-port
                  key: latest
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-domain
                  key: latest
            - name: AUTH0_ISSUER
              valueFrom:
                secretKeyRef:
                  name: auth0-issuer
                  key: latest
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-client-id
                  key: latest
            - name: AUTH0_ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: auth0-algorithms
                  key: latest
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      containerConcurrency: 25